### ISSUE TITLE
Move enable/disable toggle into existing overflow menu

### ISSUE THREAD

**Issue by arkon** [LiveTL/HyperChat#1]
Rather than having a separate button, it'd be nice if it was in YouTube's existing menu alongside the "Toggle timestamps" and "Send feedback" options.

As a sidenote, maybe the "Toggle timestamps" option should be hidden when Hyperchat is enabled since it doesn't do anything.

---

Screenshot of current UI:

<img width="401" alt="Screen Shot 2021-03-06 at 17 56 10" src="https://user-images.githubusercontent.com/4098258/110223910-422ed080-7ea5-11eb-850b-0804fbcac2cf.png">

**Comment by KentoNishi** [comment]
Is now shortened to "Enable HC"
