### ISSUE TITLE
[Bug]: Chat translation defaults to local language instead of selected target language

### ISSUE THREAD

**Issue by NeuTraLZero** [LiveTL/HyperChat#117]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

Using the "Translate chat messages using Google Translate" will always translate the chat to the current location's language instead of the selected target language from the list. (In my case the chat is always translated to Thai instead of the selected English, doesn't seem to work when I select the other languages either)

Only happened just today and I had no problem with it before

### Steps To Reproduce

1. Open HyperChat settings
2. Scroll down and enable "Translate chat messages with Google Translate"
3. Select a language from the Target language list
4. Look at the chat language

### Expected behavior

Chat should be translated to the selected language and not the local language

### What browsers are you seeing the problem on?

Firefox

**Comment by KentoNishi** [comment]
it was indeed google changing something small just to fck with us, fixed in https://github.com/KentoNishi/iframe-translator/commit/aa3d5683cfc2b7497985905b32a3fc95c45ad9cb
