### ISSUE TITLE
[Bug]: Hyperchat header positioning

### ISSUE THREAD

**Issue by menma1234** [LiveTL/HyperChat#133]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [x] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

I'm probably being A/B tested but the live chat on my account has "hide chat" moved to an X button on the top right, compared to having the wide hide chat button at the bottom, and the latest release breaks the vertical alignment of the header:

![image](https://github.com/LiveTL/HyperChat/assets/9199262/cfbb5536-7c8e-45c9-a6e4-c0749b05772c)

Everything was still fine before I got hit with the 2.6.12 update.

### Steps To Reproduce

I'm unfortunately not sure how to trigger the A/B testing but let me know if I need to dump some Javascript variables/state.

### Expected behavior

Header is properly aligned.

### What browsers are you seeing the problem on?

Firefox

**Comment by KentoNishi** [comment]
hmm, seems like the latest update fixed things in chrome but not ff. i'll fix it in the next few days

**Comment by sharkman** [comment]
I think alignment of the header is still off:
![image](https://github.com/LiveTL/HyperChat/assets/113660/6394cc36-ba53-4d75-8e38-2848b2020502)
