### ISSUE TITLE
[Bug]: MV3 Beta: Unable to interact with the chat frame via mouse.

### ISSUE THREAD

**Issue by VaporMoon** [LiveTL/HyperChat#136]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

When the Hyperchat addon is enabled I can no longer interact with the chat frame with my mouse except for the buttons in the header; Top/Live chat, HC on/off etc.

I cannot click in the chat message box, superchat, etc. I cannot scroll the chat or click on anyone's name or select any text.
I can tab around the chat frame and into the chat box just fine it's as if there is an invisible frame over the chat. I only know a few simple things so I cannot tell if/which frame is causing the issue.

This issue is still present when HC is toggled off with the header button only disabling the addon returns mouse interaction with chat.

### Steps To Reproduce

1. Go to any live chat

### Expected behavior

Being able to click on things in the chat frame.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

Tested this is in the Firefox unbranded 123.0 Nightly with Hyperchat as the only addon in a default profile.

**Comment by KentoNishi** [comment]
fixed in https://github.com/LiveTL/HyperChat/releases/tag/v2.6.14
