### ISSUE TITLE
[Bug]: Stream Guidelines gets hidden by Hyperchat (even while disabled via disable button), preventing chatting

### ISSUE THREAD

**Issue by FlaminSarge** [LiveTL/HyperChat#139]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

Hyperchat 2.6.14 on Firefox 125.0.2 (64-bit) will briefly show the Guidelines/Rules over chat, then hide it or place it underneath the chat display, depending on whether Hyperchat view is enabled or disabled. This occurs when the extension is installed, regardless of whether Hyperchat is enabled or not for that given chatbox.

### Steps To Reproduce

1) Install Hyperchat extension.
2) Load a stream for any channel for which you have not accepted the Guidelines/Rules
2b) Optionally, Enable or Disable Hyperchat using the button above chat.
3) Attempt to select the chat text entry box
4) Chat window flashes the Guidelines pane, then Hyperchat loads and hides the Guidelines pane; chatting is not possible as the Guidelines pane disables the chat entry box until accepted.

### Expected behavior

The Guidelines pane does not get hidden and behaves normally when Hyperchat ext is loaded.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

Hyperchat extension enabled, but disabled via button above chat (note the Guidelines panel appearing underneath chat):
![image](https://github.com/LiveTL/HyperChat/assets/2764675/f6c09388-f8d6-4782-9b7a-999be7ef8dbf)

Hyperchat extension enabled and Hyperchat button above chat enabled (note how the chat header is greyed out as it tried to display the Guidelines pane, disabling everything else in the chat div):
![image](https://github.com/LiveTL/HyperChat/assets/2764675/865e130c-ec78-4b32-b4a3-cf8829692dc4)

**Comment by NoamVH** [comment]
Been having this exact issue on Okayu's channel since yesterday.

I'm also using Firefox (125.0.3), and LiveTL 8.3.16.

A temporary work around until this is fixed would be to disable the LiveTL extension in Firefox, load the stream, accept the guidelines, reenable the LiveTL extension, and refresh the stream's page.

**Comment by KentoNishi** [comment]
this is pretty high priority, ill take a stab at it as soon as we're done pushing out the imminent v3 update

**Comment by sikthehedgehog** [comment]
Came here to say that this bug is still around and kicks in as soon as you click the chat input box. Firefox 127.0.2, and whatever HyperChat version comes bundled with the LiveTL 9.0.3 add-on (seems to be v3.0.0?).

I suspect that what happens is that the replaced chat is on top of the guidelines preventing them from being possible to dismiss. I may try to look at it again with the inspector if I have another opportunity (I need to find a live chat that won't let me talk first).

**Comment by jedinjapan** [comment]
Still present, and only workaround is to disable the entire extension set, agree to rules, and re-enable.

**Comment by Bigos4** [comment]
I found a workaround that doesn't require disabling the extension:
- Click the 'Disable HyperChat' button above chat.
- While the guidelines appear underneath the chat, click on the chat input field and press TAB until the 'Got it' gets selected.
- Press ENTER. The guidelines will get accepted and disappear.
- Enable HyperChat using the button above chat.

**Comment by KentoNishi** [comment]
sorry i was swamped with the iclr deadline! will properly package this up and publish soon

**Comment by FlaminSarge** [comment]
The fix https://github.com/LiveTL/HyperChat/releases/tag/v3.0.2 should be live on Chrome Web Store and Firefox Addons by now
