### ISSUE TITLE
Invisible HyperChat on Chromium-based browsers

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/HyperChat#16]
Occasionally (and pretty randomly), HyperChat fails to be rendered after the iframe is loaded on Chromium-based browsers. The iframe loads fine with no errors, chat messages are sent and received fine from the interceptor/background script, all HTML elements can be seen loaded through dev console, and even the invisible text can be selected/copied.

Seems to be related to [this Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1231231), so I guess we'll have to see if this issue gets fixed after the upstream bug report gets resolved. The only thing that's making me think that it's not just the Chromium bug is that while the example in the bug report can be consistently reproduced, it only happens seemingly randomly in our case.

Tested with both LiveTL and standalone HyperChat, on Chromium, Edge, Edge Dev and Brave. I also could not reproduce this on Firefox or Firefox Dev.

**Comment by KentoNishi** [comment]
this hasnt happened to me in a long time, has it fixed itself?

**Comment by r2dev2** [comment]
sus

**Comment by ChrRubin** [comment]
Maybe? This was a problem back in Vue HC, so maybe it was already fixed since going to Svelte lol. Closing for now.
