### ISSUE TITLE
Change color of "odd" messages

### ISSUE THREAD

**Issue by zwamdurkel** [LiveTL/HyperChat#2]
Currently, the contrast between the green text and the odd boxes is very bad from a design standpoint. the gray should be a lot darker. Even chrome's contrast utility indicates the contrast as dangerously low.
![image](https://user-images.githubusercontent.com/13705380/111011153-d662d100-8398-11eb-8b40-bd679ef47177.png)
So my suggestion is that this color should be darker, or the user should be able to set the color manually.

**Comment by ChrRubin** [comment]
Fixed since 42992e4 (LiveTL/chat#4).
