### ISSUE TITLE
Display Member Icons Next to Usernames

### ISSUE THREAD

**Issue by Flat** [LiveTL/HyperChat#20]
**Checklist (make sure you do all these before you submit a bug report)**
- [x] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [x] I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
- [x] I am not reporting a bug. If I am, I will use the bug report issue template.
- [x] I understand that I am not maintaining this codebase, and my suggestion may be rejected for any reason, including "We don't really feel like it" or "That's a little out of scope for this project" (We accept most suggestions, though.)
- [x] I also understand that even if we do accept your suggestion, it may be removed from the extension at any time, for any reason, without notification. It might not make it to a release version of the extension. 

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to see member icons (Based on length of subscription)

**Describe the solution you'd like**
Implement insertion of the proper image for members similar to how the normal YouTube chat does.

**Describe why this solution should be included in Hyperchat**
It would help to bridge the dissimilarities between Hyperchat and the default chat, it adds some eye-candy to an otherwise plain chat.

**Describe alternatives you've considered**
Implement this feature behind a setting as there are people that will only want Hyperchat for speed, which images will slow down (Not sure what the actual measured impact would be), alternatively reject the idea entirely.

**Comment by Deses** [comment]
I have installed HC v2.0.1 and I don't have options page like TL has, so I can't enable user icons, and TL has options page but not an option to enable icons. ¯\_(ツ)_/¯
