### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tordenflesk** [LiveTL/HyperChat#22]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

No chat messages appear

### Steps To Reproduce

Watch Youtube live-stream

### Expected behavior

chat messages appearing...

### What browsers are you seeing the problem on?

Other (Put it in the "Anything else?" section)

### Anything else?

Waterfox Classic 2021.10

**Comment by ChrRubin** [comment]
Waterfox Classic is running an EXTREMELY old version of Gecko/Firefox, that doesn't seem to even properly support modern  WebExtension APIs. Most extensions won't even install, let alone run properly.

Needless to say we're not providing support for a legacy browser.
