### ISSUE TITLE
[Feature] Replace svg emoji with png counterpart: 

### ISSUE THREAD

**Issue by Candygoblen123** [LiveTL/HyperChat#23]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

A performance issue with rendering a massive amount of svg files

### Describe the solution you'd like

Using the emoji I’d, we can replace the YouTube svg emoji with either a png counterpart or with the system emoji counterpart

### Expected behavior

YouTube emojis, which often get spammed, should be replaced with a png counterpart, or even better, a system emoji.

**Comment by Candygoblen123** [comment]
Here’s what we use in iOS to convert the svg to emoji:  https://github.com/LiveTL/ios/blob/f57350745dd7c82aef04e520c3d581022b8cb42f/ios/Views/StreamView/ChatCell/ChatCell.swift#L56

**Comment by Candygoblen123** [comment]
Do note that if you mess up the png path, it will go and return (and in some cases, attempt to render) the entire YouTube 404 page

**Comment by loupduqc** [comment]
regex to find the url with default svg emoji within the messages
`src="https:\/\/www\.youtube\.com\/s\/gaming\/emoji\/[a-zA-Z\d]+\/[a-zA-Z]+_[a-zA-Z\d]+\.svg`

**Comment by ChrRubin** [comment]
Seems like only "standard" emojis are being served with SVGs for now. I'd rather switch them to their unicode counterparts (which is fortunately provided in the json as alt text) than changing the URLs in case YT changes their URL schemes or something.

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/153567868-2b249ebc-e772-44af-b4b6-c34ebcf102a4.png)
 hm, perhaps we should make this an option disabled by default instead of forcing it?

**Comment by Candygoblen123** [comment]
Adding an option would also fix #46
