### ISSUE TITLE
[Feature]: Add toggle to see the user profile icons.

### ISSUE THREAD

**Issue by Deses** [LiveTL/HyperChat#24]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

It's not a problem, but I find easier to see the icons of each user, that way is easier to see at a glance the same user messages.

### Describe the solution you'd like

A toggle in the options page to enable or disable user profile icons.

### Expected behavior

When you enable the toggle, you see icons, when you disable it, you don't.

### Anything else?

I know that user icons are the most cpu intensive part of the YT chat, but if I have a beefy CPU I want to have the option to show them.

**Comment by ChrRubin** [comment]
Requires #6 to be implemented first, of which I've been slowly working on.
