### ISSUE TITLE
[Bug]: Cannot run in iframe under Edge's strict mode

### ISSUE THREAD

**Issue by a24230928** [LiveTL/HyperChat#31]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

#### Description

Hi, my HyperChat cannot execute normally in strict tracking-prevention in iframe.

When Hyper Chat got access denied to localStorage, it cannot execute normally.

![image](https://user-images.githubusercontent.com/16871628/147871858-079ba160-e350-40f4-9e09-c32654c80d4b.png)

#### Cause

I read the [document](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/tracking-prevention) briefly, and I believe it's because Edge's tracking-prevention (strict mode) will stop iframe from accessing localStorage.

![image](https://user-images.githubusercontent.com/16871628/147871881-09bc87db-11f9-4ef2-9d0c-0c04a22bf819.png)

#### Proof

And after I close strict mode of Edge's tracking-prevention, HyperChat can execute normally.

![image](https://user-images.githubusercontent.com/16871628/147872060-61ff4e57-c6ee-4d2f-b2f3-2e189066fcc2.png)

#### Possible solution

It will happen at 

https://github.com/LiveTL/HyperChat/blob/master/src/components/HyperchatButton.svelte#L4-L9

and

https://github.com/LiveTL/HyperChat/blob/39f2ab2e8db980cbad21a8b661e078635b0b237e/src/ts/chat-injector.ts#L20

Maybe can set default value or add try-catch when getting/setting localStorage value to avoid this problem, like this (I am not sure about coding style, so just a example):
```typescript
let hyperChatEnabled;
try {
    hyperChatEnabled = localStorage.getItem("HC:ENABLED") !== "false";
} catch (error) {
    console.log(error);
    hyperChatEnabled = true;
}
```

### Steps To Reproduce

1. Use Edge
2. Set Edge's tracking-prevention mode to strict (the second one from bottom) 
![image](https://user-images.githubusercontent.com/16871628/147872095-e4a72d29-68d0-49e3-bc86-a5610a088ecf.png)
3. Go to https://holodex.net/multiview
4. Open any live
![image](https://user-images.githubusercontent.com/16871628/147871995-d5a3937e-fc3b-4282-a56c-75625981f78c.png)
5. Error happen in DevTools' Console
![image](https://user-images.githubusercontent.com/16871628/147871858-079ba160-e350-40f4-9e09-c32654c80d4b.png)

### Expected behavior

HyperChat should execute like this

![image](https://user-images.githubusercontent.com/16871628/147872060-61ff4e57-c6ee-4d2f-b2f3-2e189066fcc2.png)

### What browsers are you seeing the problem on?

Microsoft Edge

### Anything else?

Some more ref
- https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document
- https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni

btw, Edge is a chromium browser after all,  I think other chromium browser will has similar problem maybe. (I haven't test yet)

**Comment by ChrRubin** [comment]
Yeah this is a known bug. We'll be ditching `localstorage` in favour of extension storage soon-ish.
