### ISSUE TITLE
Delayed messages

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/HyperChat#34]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

Apparently, many users are experiencing a thing where all messages are delayed in a live environment. This sounds like an issue of us adding too much of a delay once the chunk is received. Since live chat chunks are so frequent, can we just not add any delay to live messages? We can keep it for archived chats, but for live ones, we can just show messages instantly without worrying about timing,

### Steps To Reproduce

To find users complaining about this, just go to the Hololive fan discord and search "hyperchat."

### Expected behavior

no delay

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other (Put it in the "Anything else?" section)

**Comment by KentoNishi** [comment]
I *think* the issue is here? It's probably stacking up a lot of delays over time

https://github.com/LiveTL/HyperChat/blob/32597d93261695d905957cc9b472cca1717ab591/src/ts/queue.ts#L194-L199

**Comment by ChrRubin** [comment]
Yeah I guess we can remove that. I added that to prevent visual chat "freezes" because YTC is dumb and can sometimes send message chunks later than they're supposed to arrive, but maybe I'm just fixing a non-existent problem there.
