### ISSUE TITLE
[Bug]: No injection in development mode for firefox

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/HyperChat#35]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

When I execute `yarn start`, and load the extension in firefox, it doesn't load the "enable HC" button. It does work in chromium. When I execute `yarn build:production`, it loads in firefox.

### Steps To Reproduce

1. `yarn start`
2. load in firefox

### Expected behavior

It should inject the HC button but it doesn't.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by ChrRubin** [comment]
Might be related to SimplifyJobs/webpack-ext-reloader#90, although I don't see any errors logged on the console so it could be some other issue.

If you're wondering why I used `webpack-ext-reloader`, its cause the entire extension needs to be reloaded whenever a content/background script is modified, which happens often in HC development, and webpack's devserver + HMR just does not do that.

**Comment by rushilsrivastava** [comment]
Hi guys, I am the maintainer of `webpack-ext-reloader`. I don't think that this issue is related with https://github.com/SimplifyJobs/webpack-ext-reloader/issues/90, but I have recently fixed that issue in [`v1.1.9`](https://www.npmjs.com/package/webpack-ext-reloader/v/1.1.9). It may be a worth giving it a shot and seeing if it fixes your problem.

**Comment by r2dev2** [comment]
> Hi guys, I am the maintainer of `webpack-ext-reloader`. I don't think that this issue is related with [SimplifyJobs/webpack-ext-reloader#90](https://github.com/SimplifyJobs/webpack-ext-reloader/issues/90), but I have recently fixed that issue in [`v1.1.9`](https://www.npmjs.com/package/webpack-ext-reloader/v/1.1.9). It may be a worth giving it a shot and seeing if it fixes your problem.

Hello, upgrading to `v1.1.9` seems to fix the problem for Firefox. Thank you for the fix!
