### ISSUE TITLE
Distinguish moderators and owner from normal chat

### ISSUE THREAD

**Issue by Ryu1845** [LiveTL/HyperChat#4]
I love your extension but it would be even better if I could see at a glance when the owner or the mods were talking.

Thank you very much

**Comment by Deses** [comment]
I though this extension already did that? What does "Show moderator and owner messages" do then? Sorry, I just installed the plugin and I'm waiting for some mod to say something.

**Comment by r2dev2** [comment]
> I though this extension already did that? What does "Show moderator and owner messages" do then? Sorry, I just installed the plugin and I'm waiting for some mod to say something.

`Show moderator and owner messages` is a feature of the LiveTL extension. LiveTL bundles this repo (HyperChat) in its installation.

Also, I think @ChrRubin already implemented this feature. Should we close it @ChrRubin?

**Comment by Deses** [comment]
Yep, I realized. In fact I already had installed LiveTL. I confused both apps. I still have to see a blue chat pinned, tho! Mods are quiet today. :P

**Comment by ChrRubin** [comment]
HyperChat itself isn't really meant to be a chat filter. If you want a way to filter out mod or owner messages you should get a chat filter extension such as LiveTL.

We *could* add a toggle whenever #6 is implemented, but for now I'll close this.
