### ISSUE TITLE
[Feature]: Keep Super Chats on Top

### ISSUE THREAD

**Issue by Yay295** [LiveTL/HyperChat#49]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

I can not see Super Chats in their own bar like they are shown normally on YouTube.

### Describe the solution you'd like

YouTube, without any extensions, keeps a list of Super Chats at the top of the chat window. It would be nice to have this with HyperChat too. I expect some people wouldn't want it though, so it should probably be toggleable.

### Expected behavior

Super Chats are visible at the top of the chat window like YouTube has by default.

**Comment by KentoNishi** [comment]
this is probably next on my todo list!

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/170930956-2f873441-3c9b-4298-bad8-0c62756c8286.png)

**Comment by KentoNishi** [comment]
this is now done!
