### ISSUE TITLE
[Bug]: Live chat filter text in other localizations offsets HTML elements

### ISSUE THREAD

**Issue by risbi0** [LiveTL/HyperChat#53]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

The live chat filter text in other localization (in this case Japanese) is long enough that it offsets the HTML elements from the center.

### Steps To Reproduce

Change Youtube language to Japanese.

### Expected behavior

The HTML elements are properly centered horizontally.

### What browsers are you seeing the problem on?

Other (Put it in the "Anything else?" section)

### Anything else?

The browser I used is Brave. There might be other localizations that make the text long enough to cause this bug that I didn't bother checking.

Appearance of the live chat with Hyperchat disabled:

![01bug](https://user-images.githubusercontent.com/81689588/155368677-3ce62fbe-2060-4f34-a1c7-6bbe1c6bc346.PNG)

Appearance of the live chat with Hyperchat enabled:

![01bug1](https://user-images.githubusercontent.com/81689588/155368682-b00605c4-6689-4ac2-b5dc-1e97c95a9291.PNG)

**Comment by teduniq** [comment]
To add, this specific long text only appears in livestream VOD's and not live livestreams.

**Comment by KentoNishi** [comment]
あーぁ、日本人のくせに英語の youtube 使っているのがバレてしまいましたwww
すみません！

英語でも小さい画面では同じようなことになりそうなので、 overflow しないようなボタンの入れ方を考えておきます

**Comment by ChrRubin** [comment]
Fixed in #72.
