### ISSUE TITLE
HyperChat specific settings menu

### ISSUE THREAD

**Issue by Candygoblen123** [LiveTL/HyperChat#6]
While we have a settings menu in LiveTL, there are some settings that are specific to hyperchat that should have their own settings menu that is accessable from standalone hyperchat.

Some Ideas for settings:
- [ ]  disable the alternating lighter gray thing (@Premeditator on discord)
- [ ] Hyperchat specific Zoom
- [ ] option to default Hyperchat to off
- [ ] custom theme/color options?

**Comment by samlh** [comment]
Another option that would be nice would be a checkbox to hide the welcome message

**Comment by dreshfield** [comment]
Would it be possible to add a filter to show messages from verified users as well, not just the owner and mods? ytcFilter had an option for this, and I found it useful before I switched over to LiveTL.

**Comment by KentoNishi** [comment]
> Would it be possible to add a filter to show messages from verified users as well, not just the owner and mods? ytcFilter had an option for this, and I found it useful before I switched over to LiveTL.

good idea, but that's livetl-related. can u go ahead and make an issue [here](https://github.com/LiveTL/LiveTL)?

**Comment by dreshfield** [comment]
> > Would it be possible to add a filter to show messages from verified users as well, not just the owner and mods? ytcFilter had an option for this, and I found it useful before I switched over to LiveTL.
> 
> good idea, but that's livetl-related. can u go ahead and make an issue [here](https://github.com/LiveTL/LiveTL)?

Ah, my bad, thought it'd be a HyperChat-related thing. I'll make an issue over there.
