### ISSUE TITLE
[Bug]: The chat is wiped out randomly

### ISSUE THREAD

**Issue by eight04** [LiveTL/HyperChat#73]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

The entire chat becomes blank randomly.

### Steps To Reproduce

While this happens randomly, but seems that you can reproduce it while switching tabs:

1. Open a stream archive e.g. https://www.youtube.com/watch?v=pv6WndTSb8M
2. Wait until hyper chat is running.
3. Switch to another tab, wait one minute.
4. Switch back to the stream tab.
5. All messages disappear.

If you wait another minute, there will be some new messages popping out.

### Expected behavior

Hyper chat shouldn't clear the entire chat.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

While investigating the issue, I found that I got some messages like `Video scrubbed or skipped, forcing chat clear` from the background console.

Does it mean that all messages will be deleted when there is a browser lag? I also noticed that when switching tabs. the video freezes like 0.1s (the audio doesn't lag at all) before all messages disappear.

**Comment by ChrRubin** [comment]
Fixed in 5db4dad.
