### ISSUE TITLE
[Feature]: Hide Youtube chat's built in kebab menu when HyperChat is enabled

### ISSUE THREAD

**Issue by menma1234** [LiveTL/HyperChat#75]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

When HyperChat is enabled, the ~hamburger~ kebab menu on the Youtube chat still shows up, which IMO is confusing since none of the options in that ~hamburger~ kebab menu apply to HyperChat itself.

### Describe the solution you'd like

That ~hamburger~ kebab menu should be hidden when HyperChat is enabled and shown only if HyperChat is disabled. That makes it clear what the menu is for.

### Expected behavior

That ~hamburger~ kebab menu should be hidden when HyperChat is enabled and shown only if HyperChat is disabled. That makes it clear what the menu is for.

### Anything else?

![image](https://user-images.githubusercontent.com/9199262/167058616-fbc49351-2ed9-427c-8338-f7c846e45dc3.png)

**Comment by ChrRubin** [comment]
Other than "Toggle timestamps", all the other items have uses outside of HyperChat, so I don't think we should just hide the menu. Just hiding the "Toggle timestamps" item also seems complicated at a quick glance, cause of course YT has to make it difficult.


Also just to be pedantic that's a kebab menu, not a hamburger menu. Whoever came up with these names must've been hungry lol

**Comment by menma1234** [comment]
The only other option I see in there is "Send Feedback" which is for Youtube feedback... Kinda unintuitive I think when HyperChat's taking up the section there? It'd imply that it's for sending feedback about HyperChat.

And oops I only know the hamburger one for the 3 lines, close enough haha.

**Comment by KentoNishi** [comment]
there are quite a few more buttons 

![image](https://user-images.githubusercontent.com/38841491/167227433-760e3a87-1c8a-4d7d-8c2c-f0a3c96d8d57.png)

**Comment by KentoNishi** [comment]
dont mind the missing hc logo, im using a broken dev build lol

**Comment by menma1234** [comment]
Oh it's probably because I'm watching VODs, that makes more sense on a live stream.

**Comment by KentoNishi** [comment]
closing because this isn't really practical for livestreams.
