### ISSUE TITLE
[Bug]: Profile images for superchats aren't shown even with profile images enabled

### ISSUE THREAD

**Issue by menma1234** [LiveTL/HyperChat#76]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

When profile images are enabled in HyperChat settings, superchats don't have the profile images shown even though I would expect them to be.

### Steps To Reproduce

1. Enable profile images in HyperChat settings.
2. Have a superchat show up in chat.

### Expected behavior

Profile image is shown on the superchat.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

![image](https://user-images.githubusercontent.com/9199262/167058921-a488f811-2213-4fad-bfba-fca3abd0a500.png)

**Comment by kortik0** [comment]
How can I contribute to this issue?

**Comment by r2dev2** [comment]
> How can I contribute to this issue?

If you want to take on the issue, you can fork the repository, make the changes, and send us a pull request!

**Comment by KentoNishi** [comment]
fixed in #80 by @kortik0, thank you!
